version: 2
jobs:
  build:
    machine:
      java:
        version: openjdk8

    steps:
      - checkout

      - run:
          name: Execute build and unit tests
          command: mvn clean package

workflows:
  version: 2
  workflow:
    jobs:
      - build