version: 2
jobs:
  build:
    machine:
      java:
        version: openjdk8

    steps:
      - checkout

      - restore_cache:
          key: parkinglot-{{ checksum "pom.xml" }}

      - run:
          name: Execute build and unit tests
          command: ./mvn clean install

workflows:
  version: 2

  main:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/